/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Metodos_php.Conexion;
import java.util.Date;
public class AgendarCita extends javax.swing.JFrame {
Conexion cone;
Conexion funcion = new Conexion ();
    public AgendarCita() {
        cone = new Conexion();
        initComponents();
        llenarcombo();
//        llenarcomboj();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jcedula = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        japellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcelular = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jhorario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jcorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jinsertar = new javax.swing.JButton();
        FondoLogin = new javax.swing.JLabel();
        jtipo = new javax.swing.JComboBox<>();
        jfecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        Horario = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtipo1 = new javax.swing.JComboBox<>();
        jSexo = new javax.swing.JComboBox<>();
        jJornada = new javax.swing.JComboBox<>();
        Horario1 = new javax.swing.JLabel();
        atras_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 243, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 62, 58);

        jLabel21.setForeground(new java.awt.Color(105, 111, 121));
        jLabel21.setText("Cedula");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(100, 110, 90, 21);

        jcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcedulaActionPerformed(evt);
            }
        });
        jcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jcedula);
        jcedula.setBounds(100, 130, 330, 40);

        jLabel13.setForeground(new java.awt.Color(105, 111, 121));
        jLabel13.setText("Nombre ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(460, 110, 59, 21);

        jnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombreActionPerformed(evt);
            }
        });
        jPanel1.add(jnombre);
        jnombre.setBounds(460, 130, 330, 40);

        japellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japellidoActionPerformed(evt);
            }
        });
        jPanel1.add(japellido);
        japellido.setBounds(100, 200, 330, 40);

        jLabel10.setForeground(new java.awt.Color(105, 111, 121));
        jLabel10.setText("Apellido");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 180, 80, 21);

        jcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcelularActionPerformed(evt);
            }
        });
        jcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcelularKeyTyped(evt);
            }
        });
        jPanel1.add(jcelular);
        jcelular.setBounds(460, 200, 330, 40);

        jLabel15.setForeground(new java.awt.Color(105, 111, 121));
        jLabel15.setText("Celular");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 180, 180, 21);

        jLabel16.setForeground(new java.awt.Color(105, 111, 121));
        jLabel16.setText("Fecha De La Cita");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(100, 250, 230, 21);

        jhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhorarioActionPerformed(evt);
            }
        });
        jPanel1.add(jhorario);
        jhorario.setBounds(460, 270, 150, 40);

        jLabel18.setForeground(new java.awt.Color(105, 111, 121));
        jLabel18.setText("Tipo De Cita");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(100, 330, 180, 21);

        jcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jcorreo);
        jcorreo.setBounds(460, 360, 150, 40);

        jLabel11.setForeground(new java.awt.Color(105, 111, 121));
        jLabel11.setText("E-mail");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 340, 120, 21);

        jinsertar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jinsertar.setForeground(new java.awt.Color(255, 255, 255));
        jinsertar.setText("Insertar");
        jinsertar.setBorder(null);
        jinsertar.setBorderPainted(false);
        jinsertar.setContentAreaFilled(false);
        jinsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jinsertar.setFocusPainted(false);
        jinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertarActionPerformed(evt);
            }
        });
        jPanel1.add(jinsertar);
        jinsertar.setBounds(380, 430, 120, 50);

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/0,75.png"))); // NOI18N
        FondoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(FondoLogin);
        FondoLogin.setBounds(380, 430, 120, 60);

        jPanel1.add(jtipo);
        jtipo.setBounds(100, 360, 330, 40);

        jfecha.setDateFormatString("dd/MM/yyyy");
        jfecha.setFocusable(false);
        jPanel1.add(jfecha);
        jfecha.setBounds(100, 270, 330, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/niños.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 370, 370, 280);

        Horario.setForeground(new java.awt.Color(105, 111, 121));
        Horario.setText("Jornada");
        jPanel1.add(Horario);
        Horario.setBounds(630, 250, 100, 21);

        jLabel12.setForeground(new java.awt.Color(105, 111, 121));
        jLabel12.setText("Sexo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(630, 340, 80, 21);

        jPanel1.add(jtipo1);
        jtipo1.setBounds(100, 360, 330, 40);

        jSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Masculino", "Femenino" }));
        jSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexoActionPerformed(evt);
            }
        });
        jPanel1.add(jSexo);
        jSexo.setBounds(630, 360, 160, 40);

        jJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "AM", "PM" }));
        jPanel1.add(jJornada);
        jJornada.setBounds(630, 270, 160, 40);

        Horario1.setForeground(new java.awt.Color(105, 111, 121));
        Horario1.setText("Hora");
        jPanel1.add(Horario1);
        Horario1.setBounds(460, 250, 100, 21);

        atras_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/1.png"))); // NOI18N
        atras_btn.setBorder(null);
        atras_btn.setBorderPainted(false);
        atras_btn.setContentAreaFilled(false);
        atras_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras_btn.setDefaultCapable(false);
        atras_btn.setFocusPainted(false);
        atras_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras_ActionPerformed(evt);
            }
        });
        jPanel1.add(atras_btn);
        atras_btn.setBounds(790, 50, 20, 17);

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Datos Personales del Infante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 50, 310, 42);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 860, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/niños.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 620, 370));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/Union.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 710));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void llenarcombo(){
   
    try {
        jtipo.addItem("<<SELECCIONAR>>");
        ResultSet rs = cone.consultabd("SELECT * FROM tipo_cita");
        while (rs.next()){
            jtipo.addItem(rs.getString("nombre")); 
        }
    } catch (SQLException ex) {
        Logger.getLogger(PacienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
    }
}
//  public void llenarcomboj(){
//   
//    try {
//        jjornada.addItem("<<SELECCIONAR>>");
//        ResultSet rs = cone.consultabd("SELECT * FROM tipo_jornada");
//        while (rs.next()){
//            jjornada.addItem(rs.getString("nombre")); 
//        }
//    } catch (SQLException ex) {
//        Logger.getLogger(PacienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
//    }
//
//}
  public void limpiar(){
       jnombre.setText("");
       japellido.setText("");
       jcedula.setText("");
       jcelular.setText("");
       jcorreo.setText("");
       jhorario.setText("");
       jtipo.setSelectedIndex(0);
       jfecha.setCalendar(null);
       
   }
 
    private void jcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcorreoActionPerformed

    private void jcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcelularKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
        (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jcelularKeyTyped

    private void jcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcelularActionPerformed

    private void japellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japellidoActionPerformed

    private void jnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnombreActionPerformed

    private void jcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcedulaKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
        (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jcedulaKeyTyped

    private void jcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcedulaActionPerformed

    private void jinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertarActionPerformed
    try {
        int idtipo = 0;
//        Date date = jfecha.getDate();
//        long d = date.getTime();
//        Date fecha = new Date(d);  
        ResultSet rs = cone.consultabd("SELECT id FROM tipo_cita WHERE nombre = '"+jtipo.getSelectedItem()+"'");
        while (rs.next()){
            idtipo = rs.getInt(1);
        }
        cone.modificabd("INSERT INTO ordenes_citas(nombre,apellido,cedula,celular,correo,fecha_cita,horario,Jornada,tipo_cita_id,Sexo)"
                + "VALUES ('"+jnombre.getText()+"','"+japellido.getText()+"','"+jcedula.getText()+"','"+jcelular.getText()+"','"
                +jcorreo.getText()+"','"+funcion.getFecha(jfecha)+"','"+jhorario.getText()+"','"+jJornada.getSelectedItem()+"', "+idtipo+",'"+jSexo.getSelectedItem()+"') ");
        JOptionPane.showMessageDialog(null, " El Registro Fue Exitoso ");
    } catch (SQLException ex) {
        Logger.getLogger(PacienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
    }
limpiar();


    }//GEN-LAST:event_jinsertarActionPerformed

    private void jhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhorarioActionPerformed

    private void atras_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras_ActionPerformed
        AsistentePage2 Asis2 = new AsistentePage2();
        Asis2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atras_ActionPerformed

    private void jSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSexoActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PacienteNuevo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JLabel Horario;
    private javax.swing.JLabel Horario1;
    private javax.swing.JButton atras_btn;
    private javax.swing.JComboBox<String> jJornada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jSexo;
    private javax.swing.JTextField japellido;
    private javax.swing.JTextField jcedula;
    private javax.swing.JTextField jcelular;
    private javax.swing.JTextField jcorreo;
    private com.toedter.calendar.JDateChooser jfecha;
    private javax.swing.JTextField jhorario;
    private javax.swing.JButton jinsertar;
    private javax.swing.JTextField jnombre;
    private javax.swing.JComboBox<String> jtipo;
    private javax.swing.JComboBox<String> jtipo1;
    // End of variables declaration//GEN-END:variables
}
