/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package Interfaz;

/**
 *
 * @author maite
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form InicioAsistent
     */
    public Agenda() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon2 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        ButtonAgender = new javax.swing.JButton();
        Agendar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageNew/arrow_back_ios_24px.png"))); // NOI18N
        getContentPane().add(Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atras");
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atras.setFocusPainted(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 26, 50, 20));

        ButtonAgender.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ButtonAgender.setText("Agendar cita");
        ButtonAgender.setBorder(null);
        ButtonAgender.setBorderPainted(false);
        ButtonAgender.setContentAreaFilled(false);
        ButtonAgender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgenderActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 290, 260));

        Agendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Agendar cita.png"))); // NOI18N
        getContentPane().add(Agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dashboard.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgenderActionPerformed
                AgendarCita AgCita = new AgendarCita();
                AgCita.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_ButtonAgenderActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
      
        dispose();
    }//GEN-LAST:event_AtrasActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InicioAsistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InicioAsistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InicioAsistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InicioAsistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InicioAsistent().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agendar;
    private javax.swing.JButton Atras;
    private javax.swing.JButton ButtonAgender;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Icon2;
    // End of variables declaration//GEN-END:variables
}
