/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package Interfaz;

/**
 *
 * @author maite
 */
import Metodos_php.Conexion;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.UUID;

public class AtencionMedica extends javax.swing.JFrame {

    Conexion cone;
    Conexion funcion = new Conexion();

    public AtencionMedica() {
        cone = new Conexion();
        initComponents();
        llenarcombo();
//        llenarcomboj();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jcedula = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jdiagnostico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jinsertar = new javax.swing.JButton();
        FondoLogin = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        iSexo = new javax.swing.JComboBox<>();
        jsintomas = new javax.swing.JTextField();
        jnombre = new javax.swing.JTextField();
        japellido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jreceta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jfecha_cita = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jedad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        doctor_id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 243, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 62, 58);

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1.png"))); // NOI18N
        atras.setBorder(null);
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.setFocusPainted(false);
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        jPanel1.add(atras);
        atras.setBounds(790, 40, 30, 30);

        jcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcedulaActionPerformed(evt);
            }
        });
        jcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jcedula);
        jcedula.setBounds(130, 150, 290, 30);

        jLabel13.setForeground(new java.awt.Color(105, 111, 121));
        jLabel13.setText("Nombre :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 110, 80, 30);

        jLabel10.setForeground(new java.awt.Color(105, 111, 121));
        jLabel10.setText("Diagnostico :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 280, 100, 30);

        jdiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdiagnosticoActionPerformed(evt);
            }
        });
        jPanel1.add(jdiagnostico);
        jdiagnostico.setBounds(130, 280, 670, 130);

        jLabel11.setForeground(new java.awt.Color(105, 111, 121));
        jLabel11.setText("Síntomas :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 190, 80, 30);

        jinsertar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jinsertar.setForeground(new java.awt.Color(255, 255, 255));
        jinsertar.setText("Insertar");
        jinsertar.setBorder(null);
        jinsertar.setBorderPainted(false);
        jinsertar.setContentAreaFilled(false);
        jinsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jinsertar.setFocusPainted(false);
        jinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertarActionPerformed(evt);
            }
        });
        jPanel1.add(jinsertar);
        jinsertar.setBounds(390, 600, 120, 50);

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/0,75.png"))); // NOI18N
        FondoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(FondoLogin);
        FondoLogin.setBounds(390, 600, 120, 50);

        jLabel12.setForeground(new java.awt.Color(105, 111, 121));
        jLabel12.setText("Sexo :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(490, 150, 50, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/niños.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 330, 520, 350);

        iSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSexoActionPerformed(evt);
            }
        });
        jPanel1.add(iSexo);
        iSexo.setBounds(540, 150, 250, 30);

        jsintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsintomasActionPerformed(evt);
            }
        });
        jPanel1.add(jsintomas);
        jsintomas.setBounds(540, 190, 250, 30);

        jnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombreActionPerformed(evt);
            }
        });
        jPanel1.add(jnombre);
        jnombre.setBounds(130, 110, 290, 30);

        japellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japellidoActionPerformed(evt);
            }
        });
        jPanel1.add(japellido);
        japellido.setBounds(540, 110, 250, 30);

        jLabel14.setForeground(new java.awt.Color(105, 111, 121));
        jLabel14.setText("Apellido :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(470, 110, 80, 30);

        jLabel22.setForeground(new java.awt.Color(105, 111, 121));
        jLabel22.setText("RUT :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(80, 151, 50, 30);

        jreceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrecetaActionPerformed(evt);
            }
        });
        jPanel1.add(jreceta);
        jreceta.setBounds(130, 430, 670, 130);

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Descripción");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 240, 110, 32);

        jLabel15.setForeground(new java.awt.Color(105, 111, 121));
        jLabel15.setText("Receta :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 420, 60, 30);

        jLabel17.setForeground(new java.awt.Color(105, 111, 121));
        jLabel17.setText("Fecha De la Cita :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(520, 40, 130, 30);

        jfecha_cita.setDateFormatString("dd/MM/yyyy");
        jfecha_cita.setFocusable(false);
        jPanel1.add(jfecha_cita);
        jfecha_cita.setBounds(650, 40, 140, 30);

        jLabel16.setForeground(new java.awt.Color(105, 111, 121));
        jLabel16.setText("Edad :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(70, 190, 60, 30);

        jedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jedadActionPerformed(evt);
            }
        });
        jPanel1.add(jedad);
        jedad.setBounds(130, 190, 290, 30);

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Datos Personales del Infante");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 50, 300, 42);

        doctor_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_idActionPerformed(evt);
            }
        });
        jPanel1.add(doctor_id);
        doctor_id.setBounds(90, 10, 40, 30);

        jLabel18.setForeground(new java.awt.Color(105, 111, 121));
        jLabel18.setText("N° Doc :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 10, 60, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 860, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/Union.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 710));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/niños.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 510, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void llenarcombo() {

        try {
            iSexo.addItem("<<SELECCIONAR>>");
            ResultSet rs = cone.consultabd("SELECT * FROM tipo_sexo");
            while (rs.next()) {
                iSexo.addItem(rs.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AtencionMedica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
//  public void llenarcomboj(){
//   
//    try {
//        jjornada.addItem("<<SELECCIONAR>>");
//        ResultSet rs = cone.consultabd("SELECT * FROM tipo_jornada");
//        while (rs.next()){
//            jjornada.addItem(rs.getString("nombre")); 
//        }
//    } catch (SQLException ex) {
//        Logger.getLogger(PacienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
//    }
//
//}

    public void limpiar() {
        jnombre.setText("");
        japellido.setText("");
        jcedula.setText("");
        jedad.setText("");
        iSexo.setSelectedIndex(0);
        jfecha_cita.setCalendar(null);
        jsintomas.setText("");
        jdiagnostico.setText("");
        jreceta.setText("");
    }

    private void jdiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdiagnosticoActionPerformed

    private void jcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcedulaKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jcedulaKeyTyped

    private void jcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcedulaActionPerformed

    private void jinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertarActionPerformed
        try {
            int idtipo = 0;
 
            ResultSet rs = cone.consultabd("SELECT id FROM tipo_sexo WHERE nombre = '" + iSexo.getSelectedItem() + "'");
            while (rs.next()) {
                idtipo = rs.getInt(1);
            }
            cone.modificabd("INSERT INTO ficha(id, nombre, apellido, tipo_sexo_id, rut, edad, fecha_cita, motivo, des_diagnostico, receta, doctor_id) "
                    + "VALUES (null,'" + jnombre.getText() + "','" + japellido.getText() + "'," + idtipo + ",'" + jcedula.getText() + "','" + jedad.getText() + "','" + funcion.getFecha(jfecha_cita) + "','" + jsintomas.getText() + "','" + jdiagnostico.getText() + "','" + jreceta.getText() + "','" + doctor_id.getText() + "')");
            JOptionPane.showMessageDialog(null, "El Registro fue Exitoso!");
        } catch (SQLException ex) {
            Logger.getLogger(AtencionMedica.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();


    }//GEN-LAST:event_jinsertarActionPerformed

    private void iSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iSexoActionPerformed

    private void jsintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsintomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsintomasActionPerformed

    private void jnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnombreActionPerformed

    private void japellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japellidoActionPerformed

    private void jrecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrecetaActionPerformed

    private void jedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jedadActionPerformed

    private void doctor_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor_idActionPerformed

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        Index index = new Index();
        index.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasMouseClicked
//


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JButton atras;
    private javax.swing.JTextField doctor_id;
    private javax.swing.JComboBox<String> iSexo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField japellido;
    private javax.swing.JTextField jcedula;
    private javax.swing.JTextField jdiagnostico;
    private javax.swing.JTextField jedad;
    private com.toedter.calendar.JDateChooser jfecha_cita;
    private javax.swing.JButton jinsertar;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jreceta;
    private javax.swing.JTextField jsintomas;
    // End of variables declaration//GEN-END:variables
}
