/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package Interfaz;

/**
 *
 * @author maite
 */
import Metodos_php.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.UUID;

public class CrearFicha extends javax.swing.JFrame {
Conexion cone;
Conexion funcion = new Conexion ();
    public CrearFicha() {
        cone = new Conexion();
        initComponents();
        llenarcombo();
//        llenarcomboj();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        atras1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jcedula = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        padre_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdiagnostico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jinsertar = new javax.swing.JButton();
        FondoLogin = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        iSexo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jfecha = new com.toedter.calendar.JDateChooser();
        jalergico = new javax.swing.JTextField();
        jnombre1 = new javax.swing.JTextField();
        ficha = new javax.swing.JButton();
        japellido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 243, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Datos personales.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 60, 192, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 62, 58);

        atras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/1.png"))); // NOI18N
        atras1.setBorder(null);
        atras1.setBorderPainted(false);
        atras1.setContentAreaFilled(false);
        atras1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras1.setFocusPainted(false);
        atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras1ActionPerformed(evt);
            }
        });
        jPanel1.add(atras1);
        atras1.setBounds(790, 40, 30, 30);

        jLabel21.setForeground(new java.awt.Color(105, 111, 121));
        jLabel21.setText("RUT del Tutor");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(650, 20, 120, 21);

        jcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcedulaActionPerformed(evt);
            }
        });
        jcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jcedula);
        jcedula.setBounds(100, 130, 330, 40);

        jLabel13.setForeground(new java.awt.Color(105, 111, 121));
        jLabel13.setText("Nombre ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(460, 110, 130, 21);

        padre_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padre_idActionPerformed(evt);
            }
        });
        jPanel1.add(padre_id);
        padre_id.setBounds(610, 40, 180, 30);

        jLabel10.setForeground(new java.awt.Color(105, 111, 121));
        jLabel10.setText("Diagnóstico");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 340, 120, 21);

        jdiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdiagnosticoActionPerformed(evt);
            }
        });
        jPanel1.add(jdiagnostico);
        jdiagnostico.setBounds(100, 360, 330, 40);

        jLabel11.setForeground(new java.awt.Color(105, 111, 121));
        jLabel11.setText("Alergico A:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 260, 120, 21);

        jinsertar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jinsertar.setForeground(new java.awt.Color(255, 255, 255));
        jinsertar.setText("Insertar");
        jinsertar.setBorder(null);
        jinsertar.setBorderPainted(false);
        jinsertar.setContentAreaFilled(false);
        jinsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jinsertar.setFocusPainted(false);
        jinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertarActionPerformed(evt);
            }
        });
        jPanel1.add(jinsertar);
        jinsertar.setBounds(380, 430, 120, 50);

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/0,75.png"))); // NOI18N
        FondoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(FondoLogin);
        FondoLogin.setBounds(380, 430, 120, 60);

        jLabel12.setForeground(new java.awt.Color(105, 111, 121));
        jLabel12.setText("Sexo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 260, 80, 21);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/niños.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 280, 520, 350);

        iSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSexoActionPerformed(evt);
            }
        });
        jPanel1.add(iSexo);
        iSexo.setBounds(460, 280, 330, 40);

        jLabel16.setForeground(new java.awt.Color(105, 111, 121));
        jLabel16.setText("Fecha De Ingreso");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(460, 180, 230, 21);

        jfecha.setDateFormatString("dd/MM/yyyy");
        jfecha.setFocusable(false);
        jPanel1.add(jfecha);
        jfecha.setBounds(460, 200, 330, 40);

        jalergico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalergicoActionPerformed(evt);
            }
        });
        jPanel1.add(jalergico);
        jalergico.setBounds(100, 280, 330, 40);

        jnombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombre1ActionPerformed(evt);
            }
        });
        jPanel1.add(jnombre1);
        jnombre1.setBounds(460, 130, 330, 40);

        ficha.setText("Ver Ficha");
        ficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaActionPerformed(evt);
            }
        });
        jPanel1.add(ficha);
        ficha.setBounds(0, 500, 140, 29);

        japellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japellidoActionPerformed(evt);
            }
        });
        jPanel1.add(japellido);
        japellido.setBounds(100, 200, 330, 40);

        jLabel14.setForeground(new java.awt.Color(105, 111, 121));
        jLabel14.setText("Apellido");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(100, 180, 80, 21);

        jLabel22.setForeground(new java.awt.Color(105, 111, 121));
        jLabel22.setText("RUT");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(100, 110, 90, 21);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 860, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/Union.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -70, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/Ellipse 209.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 270, 620, 620));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void llenarcombo(){
   
    try {
        iSexo.addItem("<<SELECCIONAR>>");
        ResultSet rs = cone.consultabd("SELECT * FROM tipo_sexo");
        while (rs.next()){
            iSexo.addItem(rs.getString("nombre")); 
        }
    } catch (SQLException ex) {
        Logger.getLogger(CrearFicha.class.getName()).log(Level.SEVERE, null, ex);
    }
}
//  public void llenarcomboj(){
//   
//    try {
//        jjornada.addItem("<<SELECCIONAR>>");
//        ResultSet rs = cone.consultabd("SELECT * FROM tipo_jornada");
//        while (rs.next()){
//            jjornada.addItem(rs.getString("nombre")); 
//        }
//    } catch (SQLException ex) {
//        Logger.getLogger(PacienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
//    }
//
//}
  public void limpiar(){
       jnombre1.setText("");
       japellido.setText("");
       jcedula.setText("");
       iSexo.setSelectedIndex(0);
       jfecha.setCalendar(null);
       jalergico.setText("");
       jdiagnostico.setText(""); 
       padre_id.setText(""); 
   }
 
    private void jdiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdiagnosticoActionPerformed

    private void padre_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padre_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_padre_idActionPerformed

    private void jcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcedulaKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
        (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jcedulaKeyTyped

    private void jcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcedulaActionPerformed

    private void atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras1ActionPerformed
Doctores doctores = new Doctores();
doctores.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_atras1ActionPerformed

    private void jinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertarActionPerformed
    try {
        int idtipo = 0;
//        Date date = jfecha.getDate();
//        long d = date.getTime();
//        Date fecha = new Date(d);  
        ResultSet rs = cone.consultabd("SELECT id FROM tipo_sexo WHERE nombre = '"+iSexo.getSelectedItem()+"'");
        while (rs.next()){
            idtipo = rs.getInt(1);
        }
        cone.modificabd("INSERT INTO hijos(id,nombre,apellido,tipo_sexo_id,rut,alergico,diagnostico,fecha_cita,padre_id) "
                + "VALUES (null,'"+jnombre1.getText()+"','"+japellido.getText()+"','"+padre_id.getText()+"',"+idtipo+",'"+jcedula.getText()+"','"+jalergico.getText()+"','"+jdiagnostico.getText()+"','"+funcion.getFecha(jfecha)+"','"+padre_id.getText()+"')");
    JOptionPane.showMessageDialog(null,"El Registro fue Exitoso!");
    } catch (SQLException ex) {
        Logger.getLogger(CrearFicha.class.getName()).log(Level.SEVERE, null, ex);
    }
limpiar();


    }//GEN-LAST:event_jinsertarActionPerformed

    private void iSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iSexoActionPerformed

    private void jalergicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalergicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jalergicoActionPerformed

    private void jnombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnombre1ActionPerformed

    private void fichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaActionPerformed
        VerFicha vf = new VerFicha();
        vf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fichaActionPerformed

    private void japellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japellidoActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PacienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PacienteNuevo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JButton atras1;
    private javax.swing.JButton ficha;
    private javax.swing.JComboBox<String> iSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jalergico;
    private javax.swing.JTextField japellido;
    private javax.swing.JTextField jcedula;
    private javax.swing.JTextField jdiagnostico;
    private com.toedter.calendar.JDateChooser jfecha;
    private javax.swing.JButton jinsertar;
    private javax.swing.JTextField jnombre1;
    private javax.swing.JTextField padre_id;
    // End of variables declaration//GEN-END:variables
}
