
package Interfaz;

/**
 *
 * @author maite
 */
import Metodos_php.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class Modifica extends javax.swing.JFrame {

    Conexion cone;
    DefaultTableModel modelo;
    Conexion funcion = new Conexion();

    public Modifica() {
        cone = new Conexion();
        initComponents();
        consulta("");
        this.setLocationRelativeTo(null);
        jfecha.setVisible(false);
        jhorario.setVisible(false);
        jcedula.setVisible(false);
        jActualizar.setVisible(false);
    }

    public void limpiar() {
        jcedula.setText("");
        jhorario.setText("");
        jfecha1.setCalendar(null);
    }

    public void consulta(String buscar) {

        try {
            Conexion cone2 = new Conexion();
            String[] titulos = {"nombre", "apellido", "cedula","","", "fecha_cita", "horario", "jornada", "tipo_cita", "sexo"};
            modelo = new DefaultTableModel(null, titulos);
            ResultSet rs = cone.consultabd("SELECT * FROM ordenes_citas WHERE CONCAT (cedula, nombre,apellido, tipo_cita_id, horario,jornada) LIKE '%" + buscar + "%' ");
            String[] datos = new String[10];
            while (rs.next()) {
                datos[0] = rs.getString("nombre");
                datos[1] = rs.getString("apellido");
                datos[2] = rs.getString("cedula");
                datos[5] = rs.getString("fecha_cita");
                datos[6] = rs.getString("horario");
                datos[7] = rs.getString("jornada");
                datos[8] = rs.getString("tipo_cita_id");
                datos[9] = rs.getString("sexo");

                ResultSet rs2 = cone2.consultabd("SELECT nombre FROM tipo_cita WHERE id = " + rs.getString("tipo_cita_id") + "");
                if (rs2.next()) {
                    datos[8] = rs2.getString("nombre");
                }

                modelo.addRow(datos);

            }

            iDates.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(Modifica.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jeditar = new javax.swing.JMenuItem();
        jeliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        iDates = new javax.swing.JTable();
        Icon2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Ilustracion = new javax.swing.JLabel();
        buscar1 = new javax.swing.JTextField();
        jcedula = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jcorreo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jfecha = new javax.swing.JTextField();
        jhorario = new javax.swing.JTextField();
        jfecha1 = new com.toedter.calendar.JDateChooser();
        jfechacita = new javax.swing.JLabel();
        jActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jeditar.setText("Editar");
        jeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jeditar);

        jeliminar.setText("Eliminar");
        jeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jeliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Citas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Atras.setForeground(new java.awt.Color(134, 146, 166));
        Atras.setText("Atras");
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atras.setFocusPainted(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 26, 50, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageNew/Datos de los pacientes.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        iDates.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iDates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        iDates.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(iDates);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 760, 450));

        Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageNew/arrow_back_ios_24px.png"))); // NOI18N
        jPanel1.add(Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel17.setForeground(new java.awt.Color(105, 111, 121));
        jLabel17.setText("Busqueda");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        Ilustracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/Group 38.png"))); // NOI18N
        jPanel1.add(Ilustracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 190, -1));

        buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar1Buscar1ActionPerformed(evt);
            }
        });
        buscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar1Buscar1KeyReleased(evt);
            }
        });
        jPanel1.add(buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, 30));

        jcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcedulaActionPerformed(evt);
            }
        });
        jcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 30));

        jLabel21.setForeground(new java.awt.Color(105, 111, 121));
        jLabel21.setText("Cedula");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcorreoActionPerformed(evt);
            }
        });
        jcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcorreoKeyTyped(evt);
            }
        });
        jPanel1.add(jcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 230, 30));

        jLabel22.setForeground(new java.awt.Color(105, 111, 121));
        jLabel22.setText("Correo");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel1.add(jfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 10, -1));
        jPanel1.add(jhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 10, -1));

        jfecha1.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 190, 30));

        jfechacita.setForeground(new java.awt.Color(105, 111, 121));
        jfechacita.setText("Fecha de la cita");
        jPanel1.add(jfechacita, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 110, 30));

        jActualizar.setFont(new java.awt.Font("Dubai", 1, 15)); // NOI18N
        jActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jActualizar.setText("Actualizar");
        jActualizar.setBorderPainted(false);
        jActualizar.setContentAreaFilled(false);
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 210, 130, -1));

        jLabel3.setBackground(new java.awt.Color(0, 102, 153));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 830, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        AsistentePage2 asistentePage2 = new AsistentePage2();
        asistentePage2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AtrasActionPerformed

    private void jeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditarActionPerformed
        jcedula.setText("" + modelo.getValueAt(iDates.getSelectedRow(), 2));
        jhorario.setText("" + modelo.getValueAt(iDates.getSelectedRow(), 6));
        jfecha.setText("" + modelo.getValueAt(iDates.getSelectedRow(), 6));
        
        jfecha.setVisible(true);
        jhorario.setVisible(true);
        jcedula.setVisible(true);
        jcedula.setEditable(false);
        jActualizar.setVisible(true);
    }//GEN-LAST:event_jeditarActionPerformed

    private void jeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeliminarActionPerformed
        cone.modificabd("DELETE FROM ordenes_citas WHERE cedula = " + modelo.getValueAt(iDates.getSelectedRow(), 2));
        consulta("");
    }//GEN-LAST:event_jeliminarActionPerformed

    private void buscar1Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar1Buscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar1Buscar1ActionPerformed

    private void buscar1Buscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar1Buscar1KeyReleased
        consulta(buscar1.getText());
    }//GEN-LAST:event_buscar1Buscar1KeyReleased

    private void jcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcedulaActionPerformed

    private void jcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcedulaKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
        (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jcedulaKeyTyped

    private void jcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcorreoActionPerformed

    private void jcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jcorreoKeyTyped

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        //        Date date = jfecha.getDate();
//        long d = date.getTime();
//        Date fecha = new Date(d); 
        cone.modificabd("UPDATE ordenes_citas SET fecha_cita = '" +funcion.getFecha(jfecha1)+"',"
                                + " horario = '" +jhorario.getText()+"' WHERE cedula = " + jcedula.getText());
        consulta("");
        jfecha.setVisible(false);
        jhorario.setVisible(false);
        jcedula.setVisible(false);
        jActualizar.setVisible(false);
    }//GEN-LAST:event_jActualizarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Modifica().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel Ilustracion;
    private javax.swing.JTextField buscar1;
    private javax.swing.JTable iDates;
    private javax.swing.JButton jActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jcedula;
    private javax.swing.JTextField jcorreo;
    private javax.swing.JMenuItem jeditar;
    private javax.swing.JMenuItem jeliminar;
    private javax.swing.JTextField jfecha;
    private com.toedter.calendar.JDateChooser jfecha1;
    private javax.swing.JLabel jfechacita;
    private javax.swing.JTextField jhorario;
    // End of variables declaration//GEN-END:variables
}
