/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package Interfaz;

/**
 *
 * @author maite
 */
import Metodos_php.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class ModificarCita extends javax.swing.JFrame {
Conexion cone;
DefaultTableModel modelo;
Conexion funcion = new Conexion ();
    public ModificarCita() {
        cone = new Conexion();
        initComponents();
        consulta("");
        this.setLocationRelativeTo(null);
        jfecha.setVisible(false);
        jhorario.setVisible(false);
        jcedula.setVisible(false);
        jactualizar.setVisible(false);
    }
public void limpiar(){
       jcedula.setText("");
       jhorario.setText("");
       jfecha.setCalendar(null);
}
public void consulta (String buscar){

    try {
        Conexion cone2 = new Conexion ();
        String[] titulos = {"id","nombre","tipo_sexo_id","cedula","celular","correo"};
        modelo = new DefaultTableModel(null,titulos);
        ResultSet rs = cone.consultabd("SELECT * FROM registro_paciente WHERE CONCAT (cedula) LIKE '%"+buscar+"%' ");
        String [] datos = new String [10];
        while (rs.next()){
            datos[0]=rs.getString("id");
            datos[1]=rs.getString("nombre");
            datos[2]=rs.getString("cedula");
            datos[3]=rs.getString("celular");
            datos[4]=rs.getString("correo");
            
            
            
            ResultSet rs2 = cone2.consultabd("SELECT nombre FROM tipo_sexo WHERE id = "+rs.getString("tipo_sexo_id")+"");
            if (rs2.next()){
                datos[8] = rs2.getString("nombre");
            }
            
            modelo.addRow(datos);
            
            
        }
        
        area.setModel(modelo);
         
    } catch (SQLException ex) {
        Logger.getLogger(Modifica.class.getName()).log(Level.SEVERE, null, ex);
    }
    limpiar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jeditar = new javax.swing.JMenuItem();
        jeliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTable();
        jfecha = new com.toedter.calendar.JDateChooser();
        jfechacita = new javax.swing.JLabel();
        jhorario = new javax.swing.JTextField();
        jhorariol = new javax.swing.JLabel();
        jactualizar = new javax.swing.JButton();
        jcedula = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Ilustracion = new javax.swing.JLabel();
        Icon2 = new javax.swing.JLabel();

        jeditar.setText("Editar");
        jeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jeditar);

        jeliminar.setText("Eliminar");
        jeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jeliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Citas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Atras.setForeground(new java.awt.Color(134, 146, 166));
        Atras.setText("Atras");
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atras.setFocusPainted(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 26, 50, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageNew/Datos de los pacientes.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        area.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        area.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(area);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 760, 450));

        jfecha.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 230, -1));

        jfechacita.setForeground(new java.awt.Color(105, 111, 121));
        jfechacita.setText("Fecha de la cita");
        jPanel1.add(jfechacita, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 90, -1));

        jhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhorarioActionPerformed(evt);
            }
        });
        jPanel1.add(jhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 30));

        jhorariol.setForeground(new java.awt.Color(105, 111, 121));
        jhorariol.setText("Horario");
        jPanel1.add(jhorariol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jactualizar.setBackground(new java.awt.Color(0, 102, 102));
        jactualizar.setForeground(new java.awt.Color(255, 255, 255));
        jactualizar.setText("ACTUALIZAR");
        jactualizar.setBorder(null);
        jactualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 90, 30));

        jcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcedulaActionPerformed(evt);
            }
        });
        jcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 30));

        jLabel21.setForeground(new java.awt.Color(105, 111, 121));
        jLabel21.setText("Cedula");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        buscar.setBorder(null);
        buscar.setCaretColor(new java.awt.Color(204, 204, 204));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 230, 30));

        jLabel17.setForeground(new java.awt.Color(105, 111, 121));
        jLabel17.setText("Busqueda");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        Ilustracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/Group 38.png"))); // NOI18N
        jPanel1.add(Ilustracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 60, 190, -1));

        Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageNew/arrow_back_ios_24px.png"))); // NOI18N
        jPanel1.add(Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 830, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        InicioAsistent c = new InicioAsistent();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AtrasActionPerformed

    private void jhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhorarioActionPerformed

    private void jeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditarActionPerformed
        jcedula.setText(""+modelo.getValueAt(area.getSelectedRow(),2));
        
        jhorario.setText(""+modelo.getValueAt(area.getSelectedRow(),6));
        jfecha.setVisible(true);
        jhorario.setVisible(true);
        jcedula.setVisible(true);
        jcedula.setEditable(false);
        jactualizar.setVisible(true);
    }//GEN-LAST:event_jeditarActionPerformed

    private void jactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jactualizarActionPerformed
//        Date date = jfecha.getDate();
//        long d = date.getTime();
//        Date fecha = new Date(d); 
        cone.modificabd("UPDATE ordenes_citas SET fecha_cita = '" +funcion.getFecha(jfecha)+"',"
                                + " horario = '" +jhorario.getText()+"' WHERE cedula = " + jcedula.getText());
        consulta("");
        jfecha.setVisible(false);
        jhorario.setVisible(false);
        jcedula.setVisible(false);
        jactualizar.setVisible(false);
    }//GEN-LAST:event_jactualizarActionPerformed

    private void jcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcedulaActionPerformed

    private void jcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcedulaKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
        (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jcedulaKeyTyped

    private void jeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeliminarActionPerformed
        cone.modificabd("DELETE FROM ordenes_citas WHERE cedula = " + modelo.getValueAt(area.getSelectedRow(),2));    
        consulta("");
    }//GEN-LAST:event_jeliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    }//GEN-LAST:event_buscarActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        consulta(buscar.getText());
    }//GEN-LAST:event_buscarKeyReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Modifica().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel Ilustracion;
    private javax.swing.JTable area;
    private javax.swing.JTextField buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jactualizar;
    private javax.swing.JTextField jcedula;
    private javax.swing.JMenuItem jeditar;
    private javax.swing.JMenuItem jeliminar;
    private com.toedter.calendar.JDateChooser jfecha;
    private javax.swing.JLabel jfechacita;
    private javax.swing.JTextField jhorario;
    private javax.swing.JLabel jhorariol;
    // End of variables declaration//GEN-END:variables
}
